### ISSUE TITLE
Finished game error

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#20]
22:29:20.926 [Thread-4] INFO  - Game finished: GameFinishedEvent{}. --> org.microcol.model.ListenerManager.fireGameFinished(ListenerManager.java:89)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Game must be active.
	at org.microcol.model.GameManager.checkGameActive(GameManager.java:29)
	at org.microcol.model.GameManager.getCurrentPlayer(GameManager.java:42)
	at org.microcol.model.Model.getCurrentPlayer(Model.java:66)
	at org.microcol.gui.panelview.GamePanelView.paint(GamePanelView.java:202)

**Comment by jajir** [comment]
There are two processes, one draw game state on screen and second compute game logic. When next turn event is fired, game logic perform move. When move ends the game than event gameFinished is fired. Process of drawing game state is stoped be gameFinished but sometimes it have time to paint already finished game. It will be helpful if there will be method boolean isRunning().

**Comment by jiri-kajaba** [comment]
Method isRunning will not solve this issue (only reduce occurrences).

Relaxed precondition on getCurrentPlayer method. Now it can be called on finished game.
