### ISSUE TITLE
Reset saved preferences

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#30]
10:28:22.666 [Thread-4] INFO  - Unit moved: UnitMovedEvent{unit=Unit{type=UnitType{name=GALLEON, speed=6, canAttack=false}, owner=Player{name=Player1, computer=true}, location=Location{x=10, y=1}, availableMoves=0}, start=Location{x=4, y=2}, path=Path{locations=[Location{x=5, y=1}, Location{x=6, y=1}, Location{x=7, y=1}, Location{x=8, y=1}, Location{x=9, y=1}, Location{x=10, y=1}]}}. --> org.microcol.model.ListenerManager.fireUnitMoved(ListenerManager.java:73)
Exception in thread "Thread-4" java.lang.IllegalArgumentException: speed '9' is to high
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168)
	at org.microcol.gui.PathPlanning.countPositiveStepSize(PathPlanning.java:122)
	at org.microcol.gui.PathPlanning.countStepSize(PathPlanning.java:117)
	at org.microcol.gui.PathPlanning.countStepSize(PathPlanning.java:111)
	at org.microcol.gui.PathPlanning.paintPathWithSpeed(PathPlanning.java:101)
	at org.microcol.gui.PathPlanning.paintPath(PathPlanning.java:69)

**Comment by jajir** [comment]
Should work. With deleted preference this error shouldn't appears.

**Comment by jiri-kajaba** [comment]
It was meant to provide user way how to start game without loading saved preferences. Lets keep it closed.
